name: Build Linux ARM64

on:
  workflow_dispatch:  # 仅支持手动触发

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 安装基础依赖
      - name: Setup system
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            libgtk-3-dev:arm64 \
            libwebkit2gtk-4.0-dev:arm64 \
            libappindicator3-dev:arm64

      # 配置 Rust 工具链
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      # 设置交叉编译环境变量
      - name: Configure env
        run: |
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo 'TARGET=aarch64-unknown-linux-gnu' >> $GITHUB_ENV

      # 构建命令
      - name: Build
        run: |
          cargo build --release --target $TARGET
          strip target/$TARGET/release/gitbutler

      # 打包产物
      - name: Package
        run: |
          mkdir -p artifact
          tar czvf artifact/gitbutler-arm64.tar.gz \
            -C target/$TARGET/release \
            gitbutler

      # 上传构建结果
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitbutler-linux-arm64
          path: artifact/*