name: Linux ARM64 Build
on:
  workflow_dispatch:
    inputs:
      channel:
        description: Build channel
        required: true
        default: nightly
        type: choice
        options: [release, nightly]
      bump:
        description: Version bump type
        required: true
        default: patch
        type: choice
        options: [patch, minor, major]

jobs:
  build-sveltekit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init Node Environment
        uses: ./.github/actions/init-env-node

      - name: Set build mode
        run: |
          MODE="nightly"
          [[ "${{ github.event.inputs.channel }}" == "release" ]] && MODE="production"
          echo "BUILD_MODE=$MODE" >> $GITHUB_ENV

      - name: Build SvelteKit
        run: pnpm build:desktop -- --mode ${{ env.BUILD_MODE }}

  build-tauri:
    needs: build-sveltekit
    runs-on: ubuntu-latest
    env:
      RUST_TARGET: aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - name: Init Node Environment
        uses: ./.github/actions/init-env-node

      # 交叉编译工具链配置
      - name: Setup ARM64 Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libc6-dev-arm64-cross

          rustup target add $RUST_TARGET
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      # 版本号生成逻辑
      - name: Generate Version
        id: version
        run: |
          if [[ "${{ github.event.inputs.channel }}" == "nightly" ]]; then
            echo "VERSION=0.0.0-nightly.$(date +%Y%m%d)" >> $GITHUB_ENV
          else
            echo "VERSION=1.0.0" >> $GITHUB_ENV  # 需替换实际版本管理逻辑
          fi

      # Tauri 构建命令
      - name: Build Tauri
        run: |
          pnpm tauri build \
            --target $RUST_TARGET \
            --config "crates/gitbutler-tauri/tauri.conf.${{ github.event.inputs.channel }}.json" \
            --verbose

      # 修复点：更新 upload-artifact 到 v4+
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-arm64-${{ github.event.inputs.channel }}
          path: |
            src-tauri/target/${{ env.RUST_TARGET }}/release/bundle/*
          retention-days: 7