name: Build Tauri ARM64

on:
  push:
    branches: [main]

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 设置 Rust 环境
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: aarch64-unknown-linux-gnu
          override: true

      # 安装 ARM64 系统依赖（关键步骤）
      - name: Install cross-compile deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              gcc-aarch64-linux-gnu \
              g++-aarch64-linux-gnu \
              libgtk-3-dev:aarch64 \
              libwebkit2gtk-4.0-dev:aarch64 \
              libappindicator3-dev:aarch64

      # 配置 Node.js 环境
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      # 安装 pnpm 和项目依赖
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      # 执行 Tauri 构建（关键步骤）
      - name: Build for ARM64
        run: pnpm tauri build --target aarch64-unknown-linux-gnu

      # 收集构建产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-arm64-build
          path: |
            src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/