name: Linux ARM64 Build
on:
  workflow_dispatch:
    inputs:
      channel:
        description: Build channel
        required: true
        default: nightly
        type: choice
        options: [release, nightly]
      bump:
        description: Version bump type
        required: true
        default: patch
        type: choice
        options: [patch, minor, major]

jobs:
  build-sveltekit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init Node Environment
        uses: ./.github/actions/init-env-node  # 使用原始配置的初始化方法

      - name: Set build mode
        run: |
          MODE="nightly"
          [[ "${{ github.event.inputs.channel }}" == "release" ]] && MODE="production"
          echo "BUILD_MODE=$MODE" >> $GITHUB_ENV

      - name: Build SvelteKit
        run: pnpm build:desktop -- --mode ${{ env.BUILD_MODE }}

  build-tauri:
    needs: build-sveltekit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init Node Environment
        uses: ./.github/actions/init-env-node

      - name: Setup ARM64 Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libc6-dev-arm64-cross

      - name: Build Tauri
        run: |
          ./scripts/release.sh \
            --channel "${{ github.event.inputs.channel || 'nightly' }}" \
            --dist "./build-output" \
            --target aarch64-unknown-linux-gnu