name: Linux ARM64 Build
on:
  workflow_dispatch:
    inputs:
      channel:
        description: Build channel
        required: true
        default: nightly
        type: choice
        options: [release, nightly]
      bump:
        description: Version bump type
        required: true
        default: patch
        type: choice
        options: [patch, minor, major]

jobs:
  build-sveltekit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Init Node Environment
        uses: ./.github/actions/init-env-node

      - name: Set build mode
        run: |
          [[ "${{ github.event.inputs.channel }}" == "release" ]] && MODE="production" || MODE="nightly"
          echo "BUILD_MODE=$MODE" >> $GITHUB_ENV

      # 修复点1：明确设置前端输出路径
      - name: Build SvelteKit
        run: |
          pnpm build:desktop -- --mode ${{ env.BUILD_MODE }} --outDir ../../apps/desktop/build
          ls -la ../../apps/desktop/build  # 验证构建产物

  build-tauri:
    needs: build-sveltekit
    runs-on: ubuntu-latest
    env:
      RUST_TARGET: aarch64-unknown-linux-gnu
      FRONTEND_DIST: ../../apps/desktop/build  # 明确前端路径
    steps:
      - uses: actions/checkout@v4
      
      - name: Init Node Environment
        uses: ./.github/actions/init-env-node

      # 修复点2：配置多架构编译环境
      - name: Setup ARM64 Toolchain
        run: |
          sudo apt-get update
          sudo dpkg --add-architecture arm64
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libc6-dev-arm64-cross \
            libgtk-3-dev:arm64 \
            libwebkit2gtk-4.0-dev:arm64

          rustup target add $RUST_TARGET
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      # 修复点3：动态注入对应架构的二进制文件
      - name: Inject Git binaries
        run: |
          TRIPLE="${{ env.RUST_TARGET}}"
          SRC_DIR="./target/$TRIPLE/release"
          DEST_DIR="./crates/gitbutler-tauri"

          cp "$SRC_DIR/gitbutler-git-askpass" "$DEST_DIR/gitbutler-git-askpass-$TRIPLE"
          cp "$SRC_DIR/gitbutler-git-setsid" "$DEST_DIR/gitbutler-git-setsid-$TRIPLE"
          ls -la $DEST_DIR  # 验证文件注入

      # 修复点4：强制指定前端路径
      - name: Build Tauri
        run: |
          pnpm tauri build \
            --target $RUST_TARGET \
            --config "crates/gitbutler-tauri/tauri.conf.${{ github.event.inputs.channel }}.json" \
            --config.tauri.bundle.identifier "com.gitbutler.app" \
            --config.tauri.build.frontendDist "$FRONTEND_DIST"